{"name": "test_login_invalid_pwd", "status": "failed", "statusDetails": {"message": "AssertionError: Message doesn't display like expected\nassert False\n +  where False = <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x00000278AD610690>>('There was a problem with your login and/or errors exist in your form.')\n +    where <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x00000278AD610690>> = <pages.login_page.LoginPage object at 0x00000278AD610690>.is_display_error_mes\n +      where <pages.login_page.LoginPage object at 0x00000278AD610690> = <tests.test_login.TestLogin object at 0x00000278AD6001D0>.login_page\n +    and   'There was a problem with your login and/or errors exist in your form.' = get_message('login', 'error_login')", "trace": "self = <tests.test_login.TestLogin object at 0x00000278AD6001D0>\n\n    def test_login_invalid_pwd(self):\n        '''\n        User cannot log into Railway with invalid password.\n        :return:\n        '''\n        user = User(get_info_user(\"valid_mail\"), get_info_user(\"invalid_pwd\"))\n        self.login_page.select_tab(TabName.LOGIN.value)\n        self.login_page.login(user)\n>       assert self.login_page.is_display_error_mes(get_message(\"login\",\"error_login\")), \"Message doesn't display like expected\"\nE       AssertionError: Message doesn't display like expected\nE       assert False\nE        +  where False = <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x00000278AD610690>>('There was a problem with your login and/or errors exist in your form.')\nE        +    where <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x00000278AD610690>> = <pages.login_page.LoginPage object at 0x00000278AD610690>.is_display_error_mes\nE        +      where <pages.login_page.LoginPage object at 0x00000278AD610690> = <tests.test_login.TestLogin object at 0x00000278AD6001D0>.login_page\nE        +    and   'There was a problem with your login and/or errors exist in your form.' = get_message('login', 'error_login')\n\ntests\\test_login.py:48: AssertionError"}, "description": "\n        User cannot log into Railway with invalid password.\n        :return:\n        ", "attachments": [{"name": "screenshot", "source": "a0026fe8-c81c-40ca-9e19-6a7c727e6c4d-attachment.png", "type": "image/png"}], "start": 1721016929965, "stop": 1721016931637, "uuid": "3b2a5ec8-7459-432a-ab33-a453e60f1c3d", "historyId": "100ccbdb43bda6e72274a719705810b8", "testCaseId": "100ccbdb43bda6e72274a719705810b8", "fullName": "tests.test_login.TestLogin#test_login_invalid_pwd", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DUYEN"}, {"name": "thread", "value": "18708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}