{"uuid": "2c07e332-2c13-45a5-b43f-99f7c8ab77d2", "children": ["be25031c-5e65-4a55-9809-135bbd174345", "315f99f1-27dd-4911-952e-4a03aa9f1d09", "3f23cdbc-683f-48f8-9a10-653b3d1ba415", "77691065-7700-4732-b4a8-f5299059a332", "80de6924-4162-4823-8f0e-95706b4fb0dc"], "befores": [{"name": "setup_and_teardown", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in module-scoped context\n", "trace": "  File \"C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"F:\\AGEST\\Selenium\\SeleniumPython\\tests\\conftest.py\", line 20, in setup_and_teardown\n    if request.cls is not None:\n       ^^^^^^^^^^^\n  File \"C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 435, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1721027562416, "stop": 1721027609696}], "start": 1721027562416, "stop": 1721027609851}