{"name": "test_login_invalid_pwd", "status": "failed", "statusDetails": {"message": "AssertionError: Message doesn't display like expected\nassert False\n +  where False = <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x0000025721463AD0>>('There was a problem with your login and/or errors exist in your form.')\n +    where <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x0000025721463AD0>> = <pages.login_page.LoginPage object at 0x0000025721463AD0>.is_display_error_mes\n +      where <pages.login_page.LoginPage object at 0x0000025721463AD0> = <tests.test_login.TestLogin object at 0x00000257214602D0>.login_page\n +    and   'There was a problem with your login and/or errors exist in your form.' = get_message('login', 'error_login')", "trace": "self = <tests.test_login.TestLogin object at 0x00000257214602D0>\n\n    def test_login_invalid_pwd(self):\n        '''\n        User cannot log into Railway with invalid password.\n        :return:\n        '''\n        user = User(get_info_user(\"valid_mail\"), get_info_user(\"invalid_pwd\"))\n        self.login_page.select_tab(TabName.LOGIN.value)\n        self.login_page.login(user)\n>       assert self.login_page.is_display_error_mes(get_message(\"login\",\"error_login\")), \"Message doesn't display like expected\"\nE       AssertionError: Message doesn't display like expected\nE       assert False\nE        +  where False = <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x0000025721463AD0>>('There was a problem with your login and/or errors exist in your form.')\nE        +    where <bound method LoginPage.is_display_error_mes of <pages.login_page.LoginPage object at 0x0000025721463AD0>> = <pages.login_page.LoginPage object at 0x0000025721463AD0>.is_display_error_mes\nE        +      where <pages.login_page.LoginPage object at 0x0000025721463AD0> = <tests.test_login.TestLogin object at 0x00000257214602D0>.login_page\nE        +    and   'There was a problem with your login and/or errors exist in your form.' = get_message('login', 'error_login')\n\ntests\\test_login.py:48: AssertionError"}, "description": "\n        User cannot log into Railway with invalid password.\n        :return:\n        ", "attachments": [{"name": "screenshot", "source": "d6bdd1ff-a16d-4b15-baef-045d5ea6cdbf-attachment.png", "type": "image/png"}], "start": 1721017031230, "stop": 1721017033305, "uuid": "49156bd6-52a5-4a7c-bf97-a8f199fc18f2", "historyId": "100ccbdb43bda6e72274a719705810b8", "testCaseId": "100ccbdb43bda6e72274a719705810b8", "fullName": "tests.test_login.TestLogin#test_login_invalid_pwd", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DUYEN"}, {"name": "thread", "value": "19748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}