{"name": "test_login_wrong_pws_manytime", "status": "failed", "statusDetails": {"message": "AssertionError: Time 1: Message doesn't display like expect.\nTime 2: Message doesn't display like expect.\nTime 3: Message doesn't display like expect.\nTime 4: Message doesn't display like expect.\nTime 5: Message doesn't display like expect.\nMessage which displays to info user that they will unable to login for 15m doesn't appears.", "trace": "self = <tests.test_login.TestLogin object at 0x00000278AD600910>\n\n    def test_login_wrong_pws_manytime(self):\n        '''\n        System shows message when user enters wrong password many times.\n        :return:\n        '''\n        user = User(get_info_user(\"valid_mail\"), get_info_user(\"invalid_pwd\"))\n        soft_assert = SoftAssert()\n        self.login_page.login_manytime(user, 5, soft_assert, get_message(\"login\",\"error_mail_pwd\"))\n        soft_assert.check(self.login_page.is_display_error_mes(get_message(\"login\",\"error_login_manytime\")), \"Message which displays to info user that they will unable to login for 15m doesn't appears.\")\n>       soft_assert.assert_all()\n\ntests\\test_login.py:59: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <helper.soft_assert.SoftAssert object at 0x00000278AD66C3D0>\n\n    def assert_all(self):\n        if self.errors:\n>           raise AssertionError('\\n'.join(self.errors))\nE           AssertionError: Time 1: Message doesn't display like expect.\nE           Time 2: Message doesn't display like expect.\nE           Time 3: Message doesn't display like expect.\nE           Time 4: Message doesn't display like expect.\nE           Time 5: Message doesn't display like expect.\nE           Message which displays to info user that they will unable to login for 15m doesn't appears.\n\nhelper\\soft_assert.py:11: AssertionError"}, "description": "\n        System shows message when user enters wrong password many times.\n        :return:\n        ", "attachments": [{"name": "screenshot", "source": "898e4682-ab6b-4f39-9b85-dd0e668e51a8-attachment.png", "type": "image/png"}], "start": 1721016932017, "stop": 1721016940998, "uuid": "806a221a-24d7-4092-a244-fabc46e5781c", "historyId": "4e96d6e7442c6f05e9317ee924afd076", "testCaseId": "4e96d6e7442c6f05e9317ee924afd076", "fullName": "tests.test_login.TestLogin#test_login_wrong_pws_manytime", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DUYEN"}, {"name": "thread", "value": "18708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}